services:
  codely_oracle_rrss_database:
    container_name: codely_oracle_rrss_database
    image: gvenzl/oracle-free:23.3
    environment:
      ORACLE_RANDOM_PASSWORD: true
      APP_USER: codely
      APP_USER_PASSWORD: C0d3lyS3cr3t
    ports:
      - 1521:1521
    volumes:
      - ./database/1-base.sql:/container-entrypoint-initdb.d/1-base.sql
    options: >-
      --health-cmd healthcheck.sh
      --health-interval 10s
      --health-timeout 5s
      --health-retries 10
