services:
  codely_pg_rrss_database_1:
    container_name: codely-pg-rrss-database-1
    image: "postgres:15-alpine"
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=C0d3lyS3cr3t
    volumes:
      - ./database/1-base.sql:/docker-entrypoint-initdb.d/00_init_db.sql
