services:
  codely_sqlserver_rrss_database:
    container_name: codely_sqlserver_rrss_database
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "C0d3lyS3cr3t"
    ports:
      - "1433:1433"
